import os

# Lista com a sintaxe do Python para todas as chaves e valores
bancoDadosTemas = [
    { "nome": "101 Dálmatas", "pasta": "101dalmatas", "categorias": "all animais desenhos" },
    { "nome": "Hulk", "pasta": "hulk", "categorias": "all herois meninos" },
    { "nome": "Ariel", "pasta": "ariel", "categorias": "all princesas disney" },
    { "nome": "Ana Castela", "pasta": "anacastela", "categorias": "all boiadeira musica" },
    { "nome": "Animatronics", "pasta": "animatronics", "categorias": "all jogos" },
    { "nome": "15 anos", "pasta": "15anos", "categorias": "all diversos" },
    { "nome": "3 Palavrinhas", "pasta": "3palavrinhas", "categorias": "all religiosos" },
    { "nome": "Abelhinha", "pasta": "abelhinha", "categorias": "all animais desenhos" },
    { "nome": "Alice no pais das maravilhas", "pasta": "alicenopaisdasmaravilhas", "categorias": "all princesas contodefadas filme disney" },
    { "nome": "Ano novo", "pasta": "anonovo", "categorias": "all anonovo fimdeano datacomemorativa" },
    { "nome": "Arco Vazado Simples", "pasta": "arcovazado_simples", "categorias": "all arcovazado" },
    { "nome": "Arco Vazado Desconstruído", "pasta": "arcovazado_desconstruido", "categorias": "all arcovazado" },
    { "nome": "Arraia marron", "pasta": "arraiamarrom", "categorias": "all arraia datacomemorativa" },
    { "nome": "Arraia rosa", "pasta": "arraiarosa", "categorias": "all arraia datacomemorativa" },
    { "nome": "Asa neon", "pasta": "asaneon", "categorias": "all diversos" },
    { "nome": "Astronauta", "pasta": "astronauta", "categorias": "all espaco desenhos" },
    { "nome": "Baby Shark", "pasta": "babyshark", "categorias": "all fundodomar desenhos musica" },
    { "nome": "Barbie", "pasta": "barbie", "categorias": "all meninos desenhos filme boneca" },
    { "nome": "Batizado", "pasta": "batizado", "categorias": "all religiosos batizado" },
    { "nome": "Batizado azul", "pasta": "batizadoazul", "categorias": "all religiosos batizado" },
    { "nome": "Batizado Beje", "pasta": "batizadobeje", "categorias": "all religiosos batizado" },
    { "nome": "Batizado Lilas", "pasta": "batizadolilas", "categorias": "all religiosos batizado" },
    { "nome": "Batizado Rosa", "pasta": "batizadorosa", "categorias": "all religiosos batizado" },
    { "nome": "Batizado Verde", "pasta": "batizadoverde", "categorias": "all religiosos batizado" },
    { "nome": "Batizado Anjinho", "pasta": "batizadoanjinho", "categorias": "all religiosos batizado" },
    { "nome": "Batizado Divino Espirito Santo", "pasta": "batizandodivinoespiritosanto", "categorias": "all religiosos batizado" },
    { "nome": "Batman", "pasta": "batman", "categorias": "all herois filme desenhos" },
    { "nome": "Bee movie", "pasta": "beemovie", "categorias": "all filme animais" },
    { "nome": "Bela adormecida", "pasta": "belaadormecida", "categorias": "all princesas contodefadas filme disney" },
    { "nome": "Bela e a Fera", "pasta": "belaeafera", "categorias": "all princesas contodefadas filme disney" },
    { "nome": "Bento e Totó", "pasta": "bentoetoto", "categorias": "all princesas contodefadas filme disney" },
    { "nome": "BeyBlade", "pasta": "beyblade", "categorias": "all desenhos" },
    { "nome": "Blazze", "pasta": "blazze", "categorias": "all corrida desenhos" },
    { "nome": "Bluey e bingo", "pasta": "blueyebingo", "categorias": "all desenhos animais" },
    { "nome": "Bluey e bingo aniversario", "pasta": "blueyebingoaniversario", "categorias": "all desenhos animais" },
    { "nome": "Bob Esponja", "pasta": "bobesponja", "categorias": "all desenhos fundodomar" },
    { "nome": "Borboleta Roxa", "pasta": "borboletaroxa", "categorias": "all borboletas animais" },
    { "nome": "Borboletas Azuis", "pasta": "borboletasazuis", "categorias": "all borboletas animais" },
    { "nome": "Boiadeira", "pasta": "boiadeira", "categorias": "all boiadeira" },
    { "nome": "Bolofofos", "pasta": "bolofofos", "categorias": "all desenhos musicas" },
    { "nome": "Bombeiro", "pasta": "bombeiro", "categorias": "all bombeiro" },
    { "nome": "Bobbie Goods", "pasta": "bobbiegoods", "categorias": "all diversos" },
    { "nome": "Bosque", "pasta": "bosque", "categorias": "all diversos" },
    { "nome": "Bosque Encantado", "pasta": "bosqueencantado", "categorias": "all diversos cute animais" },
    { "nome": "Boteco", "pasta": "boteco", "categorias": "all boteco diversos" },
    { "nome": "Boteco cerveja", "pasta": "botecocerveja", "categorias": "all boteco diversos" },
    { "nome": "Branca de neve", "pasta": "brancadeneve", "categorias": "all princesas contodefadas filme disney" },
    { "nome": "Branca de neve cute", "pasta": "brancadenevecute", "categorias": "all princesas contodefadas filme disney cute" },
    { "nome": "BTS", "pasta": "bts", "categorias": "all k-pop musica" },
    { "nome": "Caminhao", "pasta": "caminhao", "categorias": "all diversos desenhos veiculos" },
    { "nome": "Capitao America", "pasta": "capitaoamerica", "categorias": "all herois filme desenhos" },
    { "nome": "Capivara", "pasta": "capivara", "categorias": "all animais diversos" },
    { "nome": "Casa magica da gabby", "pasta": "casamagicadagabby", "categorias": "all desenhos magia" },
    { "nome": "Castelo Ra-tim-bum", "pasta": "casteloratimbum", "categorias": "all desenhos diversos" },
    { "nome": "Cavalo", "pasta": "cavalo", "categorias": "all animais" },
    { "nome": "Cerejinha", "pasta": "cerejinha", "categorias": "all frutas" },
    { "nome": "Cha de bebe azul", "pasta": "chadebebeazul", "categorias": "all chadebebe" },
    { "nome": "Cha de bebe lilas", "pasta": "chadebebelilas", "categorias": "all chadebebe" },
    { "nome": "Cha de bebe rosa", "pasta": "chadebeberosa", "categorias": "all chadebebe" },
    { "nome": "Cha de bebe verde", "pasta": "chadebebeverde", "categorias": "all chadebebe" },
    { "nome": "Cha de bebe arraia rosa", "pasta": "chadebebearraiarosa", "categorias": "all chadebebe personalizada" },
    { "nome": "Cha de Casa Nova", "pasta": "chadecasanova", "categorias": "all chadecasanova" },
    { "nome": "Cha de Lingerie", "pasta": "chalingerie", "categorias": "all chalingerie" },
    { "nome": "Cha de Panela", "pasta": "chapanela", "categorias": "all chapanela" },
    { "nome": "Cha Revelacao", "pasta": "charevelacao", "categorias": "all charevelacao" },
    { "nome": "Cha Revelacao meninos meninas", "pasta": "charevelacaomeninosmeninas", "categorias": "all charevelacao" },
    { "nome": "Cha Revelacao urso azul e rosa", "pasta": "charevelacaoursoazulerosa", "categorias": "all charevelacao" },
    { "nome": "Cha Revelacao urso roxo e verde", "pasta": "charevelacaoursoroxoeverde", "categorias": "all charevelacao" },
    { "nome": "Chaves baby", "pasta": "chavesbaby", "categorias": "all desenhos" },
    { "nome": "Cinderela", "pasta": "cinderela", "categorias": "all princesas filme contodefadas disney" },
    { "nome": "Circo Rosa", "pasta": "circorosa", "categorias": "all circo" },
    { "nome": "Corinthians", "pasta": "corinthians", "categorias": "all times futebol" },
    { "nome": "Churrasco", "pasta": "churrasco", "categorias": "all churrasco" },
    { "nome": "CR7", "pasta": "cr7", "categorias": "all futebol jogador" },
    { "nome": "Demon Slayer", "pasta": "demonslayer", "categorias": "all anime" },
    { "nome": "De repente 30", "pasta": "derepente30", "categorias": "all diversos" },
    { "nome": "Dia das Maes", "pasta": "diadasmaes", "categorias": "all datacomemorativa" },
    { "nome": "Dia dos Pais", "pasta": "diadospais", "categorias": "all datacomemorativa" },
    { "nome": "Dinossauro", "pasta": "dinossauro", "categorias": "all dinossauro animais" },
    { "nome": "Dinossauros Baby", "pasta": "dinossaurosbaby", "categorias": "all dinossauro animais" },
    { "nome": "Divertidamente", "pasta": "divertidamente", "categorias": "all filme contodefadas" },
    { "nome": "Doceria", "pasta": "doceria", "categorias": "all doces diversos" },
    { "nome": "Dragon Ball", "pasta": "dragonball", "categorias": "all desenhos" },
    { "nome": "Enaldinho", "pasta": "enaldinho", "categorias": "all youtuber" },
    { "nome": "Enrolados", "pasta": "enrolados", "categorias": "all princesas contodefadas filme" },
    { "nome": "Eu amo tete menina", "pasta": "euamotetemenina", "categorias": "all cute diversos" },
    { "nome": "Eu amo tete menino", "pasta": "euamotetemenino", "categorias": "all cute diversos" },
    { "nome": "Fazendinha azul", "pasta": "fazendinhaazul", "categorias": "all fazendinha" },
    { "nome": "Fazendinha rosa", "pasta": "fazendinharosa", "categorias": "all fazendinha" },
    { "nome": "Fazendinha vermelha", "pasta": "fazendinhavermelha", "categorias": "all fazendinha" },
    { "nome": "Festa Junina", "pasta": "festajunina", "categorias": "all arraia" },
    { "nome": "Fini fundo branco", "pasta": "finifundobranco", "categorias": "all doces diversos" },
    { "nome": "Fini fundo vermelho", "pasta": "finifundovermelho", "categorias": "all doces diversos" },
    { "nome": "Flamengo", "pasta": "flamengo", "categorias": "all times futebol" },
    { "nome": "Flamingo", "pasta": "flamingo", "categorias": "all animais" },
    { "nome": "Flor Lilas e borboleta", "pasta": "florlilaseborboleta", "categorias": "all flores borboletas" },
    { "nome": "Flork eu te amo", "pasta": "florkeuteamo", "categorias": "all diversos" },
    { "nome": "Free Fire", "pasta": "freefire", "categorias": "all jogos" },
    { "nome": "Frozen", "pasta": "frozen", "categorias": "all princesas filme contodefadas disney" },
    { "nome": "Fundo do mar", "pasta": "fundodomar", "categorias": "all fundodomar" },
    { "nome": "Futebol", "pasta": "futebol", "categorias": "all times futebol" },
    { "nome": "Futebol menina", "pasta": "futebolmenina", "categorias": "all times futebol feminino" },
    { "nome": "Frutas", "pasta": "frutas", "categorias": "all frutas" },
    { "nome": "Galinha Pintadinha", "pasta": "galinhapintadinha", "categorias": "all desenhos musica" },
    { "nome": "Gamer", "pasta": "gamer", "categorias": "all game diversos" },
    { "nome": "Gi Turma Luccas Neto", "pasta": "giturmaluccasneto", "categorias": "all youtuber desenhos" },
    { "nome": "Godzilla vs King Kong", "pasta": "godzillavskingkong", "categorias": "all filme contodefadas" },
    { "nome": "Gratidao", "pasta": "gratidao", "categorias": "all diversos" },
    { "nome": "Grinch", "pasta": "grinch", "categorias": "all filme" },
    { "nome": "Guerreiras do K-pop", "pasta": "guerreirasdokpop", "categorias": "all k-pop musica filme" },
    { "nome": "Halloween abobora", "pasta": "halloweenabobora", "categorias": "all datacomemorativa halloween" },
    { "nome": "Halloween castelo laranja", "pasta": "halloweencastelolaranja", "categorias": "all datacomemorativa halloween" },
    { "nome": "Halloween castelo roxo", "pasta": "halloweencasteloroxo", "categorias": "all datacomemorativa halloween" },
    { "nome": "Happy Birthday Glitter Pink", "pasta": "happybirthdayglitterpink", "categorias": "all happybirthday glitter" },
    { "nome": "Happy Birthday azul arabesco dourado", "pasta": "happybirthdayazularabescodourado", "categorias": "all happybirthday glitter" },
    { "nome": "Happy Birthday glitter Rose", "pasta": "happybirthdayglitterrose", "categorias": "all happybirthday glitter" },
    { "nome": "Happy Birthday azul e Prata", "pasta": "happybirthdayazuleprata", "categorias": "all happybirthday" },
    { "nome": "Happy Birthday lantejoula lilas", "pasta": "happybirthdaylantejoulalilas", "categorias": "all happybirthday" },
    { "nome": "Happy Birthday lantejoula rosa", "pasta": "happybirthdaylantejoularosa", "categorias": "all happybirthday" },
    { "nome": "Happy Birthday preto e Dourado", "pasta": "happybirthdaypretoedourado", "categorias": "all happybirthday" },
    { "nome": "Happy Birthday vermelho e dourado", "pasta": "happybirthdayvermelhoedourado", "categorias": "all happybirthday" },
    { "nome": "Happy Birthday rosa", "pasta": "happybirthdayrosa", "categorias": "all happybirthday" },
    { "nome": "Happy Birthday Marssala", "pasta": "happybirthdaymarssala", "categorias": "all happybirthday" },
    { "nome": "Happy Birthday Laranja e pink", "pasta": "happybirthdaylaranjaepink", "categorias": "all happybirthday" },
    { "nome": "Harry Potter", "pasta": "harrypotter", "categorias": "all filme contodefadas magia" },
    { "nome": "Hello Kitty", "pasta": "hellokitty", "categorias": "all desenhos" },
    { "nome": "Homem Aranha", "pasta": "homemaranha", "categorias": "all herois filme" },
    { "nome": "Homem Aranha Cute", "pasta": "homemarancute", "categorias": "all herois filme cute" },
    { "nome": "Homem de Ferro", "pasta": "homemdeferro", "categorias": "all herois filme" },
    { "nome": "HotWheels", "pasta": "hotwheels", "categorias": "all corrida desenhos veiculos" },
    { "nome": "Ilhama", "pasta": "ilhama", "categorias": "all animais" },
    { "nome": "Illit", "pasta": "illit", "categorias": "all k-pop musica" },
    { "nome": "Jardim de Borboletas", "pasta": "jardimdeborboletas", "categorias": "all jardim borboletas" },
    { "nome": "Kuromi e Melody", "pasta": "kuromiemelody", "categorias": "all desenhos" },
    { "nome": "Laços", "pasta": "laços", "categorias": "all lacos" },
    { "nome": "Labubu menina", "pasta": "labubumenina", "categorias": "all desenhos" },
    { "nome": "Labubu menino", "pasta": "labubumenino", "categorias": "all desenhos" },
    { "nome": "lacinho rosa preto e prata", "pasta": "lacinhosapretaeprata", "categorias": "all festapersonalizada laco" },
    { "nome": "lacinho rosa preto e branco", "pasta": "lacinhosapretaebranco", "categorias": "all festapersonalizada laco" },
    { "nome": "Lady Budy", "pasta": "ladybudy", "categorias": "all desenhos filme" },
    { "nome": "Lanterna Verde", "pasta": "lanternaverde", "categorias": "all herois filme" },
    { "nome": "Lantejoula", "pasta": "lantejoula", "categorias": "all lantejoula natal" },
    { "nome": "Lavanda", "pasta": "lavanda", "categorias": "all flores" },
    { "nome": "Liga da Justica baby", "pasta": "ligadajusticababy", "categorias": "all herois cute" },
    { "nome": "lilas Glitter", "pasta": "lilasglitter", "categorias": "all glitter" },
    { "nome": "Liso amarelo", "pasta": "lisoamarelo", "categorias": "all cores" },
    { "nome": "Liso azul claro", "pasta": "lisoazulclaro", "categorias": "all cores" },
    { "nome": "Liso Azul e Prata", "pasta": "lisoazuleprata", "categorias": "all cores" },
    { "nome": "Liso azul royal", "pasta": "lisoazulroyal", "categorias": "all cores" },
    { "nome": "Liso branco", "pasta": "lisobranco", "categorias": "all liso cores" },
    { "nome": "Liso laranja", "pasta": "lisolaranja", "categorias": "all cores" },
    { "nome": "Liso lilas", "pasta": "lisolilas", "categorias": "all cores" },
    { "nome": "Liso pirulito lilas com borboletas", "pasta": "lisopirulitolilascomborboletas", "categorias": "all cores personalizadas" },
    { "nome": "Liso pink", "pasta": "lisopink", "categorias": "all cores" },
    { "nome": "Liso preto", "pasta": "lisopreto", "categorias": "all cores" },
    { "nome": "Liso rosa", "pasta": "lisorosa", "categorias": "all cores" },
    { "nome": "Liso pirulito rosa", "pasta": "lisopirulitorosa", "categorias": "all cores" },
    { "nome": "Liso pirulito azul bebe", "pasta": "lisopirulitoazulbebe", "categorias": "all cores" },
    { "nome": "Liso pirulito verde exercito", "pasta": "lisopirulitoverdeexercito", "categorias": "all cores" },
    { "nome": "Liso pirulito branco", "pasta": "lisopirulitobranco", "categorias": "all cores" },
    { "nome": "Liso pirulito azul royal", "pasta": "lisopirulitoazulroyal", "categorias": "all cores" },
    { "nome": "Liso pirulito rose", "pasta": "lisopirulitorose", "categorias": "all cores" },
    { "nome": "Liso pirulito lilas", "pasta": "lisopirulitolilas", "categorias": "all cores" },
    { "nome": "Magali", "pasta": "magali", "categorias": "all desenhos" },
    { "nome": "Margarida", "pasta": "margarida", "categorias": "all flores" },
    { "nome": "Maria Clara e JP", "pasta": "mariaclaraejp", "categorias": "all youtuber desenhos" },
    { "nome": "Masha e o Urso", "pasta": "mashaeourso", "categorias": "all desenhos" },
    { "nome": "Meu mundo doce com Jesus", "pasta": "meumundodocecomjesus", "categorias": "all religiosos" },
    { "nome": "Mickey", "pasta": "mickey", "categorias": "all desenhos disney" },
    { "nome": "MineCraft", "pasta": "minecraft", "categorias": "all jogos" },
    { "nome": "Minha primeira volta ao sol", "pasta": "minhaprimeiravoltaaosol", "categorias": "all diversos" },
    { "nome": "Minions", "pasta": "minions", "categorias": "all filme desenhos" },
    { "nome": "Minions 2", "pasta": "minions2", "categorias": "all filme desenhos" },
    { "nome": "Minnie rosa", "pasta": "minnierosa", "categorias": "all desenhos disney" },
    { "nome": "Minnie vermelha", "pasta": "minnievermelha", "categorias": "all desenhos disney" },
    { "nome": "Moana", "pasta": "moana", "categorias": "all princesas filme contodefadas disney" },
    { "nome": "Moana 2", "pasta": "moana2", "categorias": "all princesas filme contodefadas disney" },
    { "nome": "Moana baby", "pasta": "moanababy", "categorias": "all princesas filme contodefadas cute disney" },
    { "nome": "Monstros SA", "pasta": "monstrossa", "categorias": "all desenhos filme disney" },
    { "nome": "Mulher Maravilha", "pasta": "mulhermaravilha", "categorias": "all herois filme" },
    { "nome": "Mundo Bita", "pasta": "mundobita", "categorias": "all desenhos musica" },
    { "nome": "Naruto", "pasta": "naruto", "categorias": "all anime" },
    { "nome": "Natal", "pasta": "natal", "categorias": "all natal datacomemorativa" },
    { "nome": "Noivado", "pasta": "noivado", "categorias": "all noivado" },
    { "nome": "NumberBlocks", "pasta": "numberblocks", "categorias": "all desenhos" },
    { "nome": "Palmeiras", "pasta": "palmeiras", "categorias": "all times futebol" },
    { "nome": "Pantera Negra", "pasta": "panteranegra", "categorias": "all herois filme" },
    { "nome": "Patati e Patata", "pasta": "patatiepatata", "categorias": "all desenhos musicas" },
    { "nome": "Patinho Colorido", "pasta": "patinhocolorido", "categorias": "all desenhos musica" },
    { "nome": "Patrulha Canina", "pasta": "patrulhacanina", "categorias": "all animais desenhos" },
    { "nome": "Pepa pig", "pasta": "pepapig", "categorias": "all desenhos animais" },
    { "nome": "Pequeno Principe", "pasta": "pequenoprincipe", "categorias": "all desenhos" },
    { "nome": "Personalizado", "pasta": "personalizado", "categorias": "all personalizados" },
    { "nome": "PjMask", "pasta": "pjmask", "categorias": "all desenhos" },
    { "nome": "Pocoyo", "pasta": "pocoyo", "categorias": "all desenhos" },
    { "nome": "Poderosa Chefinha", "pasta": "poderosachefinha", "categorias": "all filme desenhos" },
    { "nome": "Poderoso Chefinho", "pasta": "poderosochefinho", "categorias": "all filme desenhos" },
    { "nome": "Pokemon", "pasta": "pokemon", "categorias": "all desenhos animais" },
    { "nome": "Pool Party Rosa", "pasta": "poolpartyrosa", "categorias": "all piscina" },
    { "nome": "Princesa Tiana", "pasta": "princesatiana", "categorias": "all disney filme desenhos" },
    { "nome": "Princesas Disney", "pasta": "princesasdisney", "categorias": "all disney filme desenhos" },
    { "nome": "raposinha", "pasta": "raposinha", "categorias": "all animais" },
    { "nome": "Rei Leao", "pasta": "reileao", "categorias": "all animais desenhos filme" },
    { "nome": "Relampago Mcqueen", "pasta": "relampagomcqueen", "categorias": "all filme corrida veiculos" },
    { "nome": "Roblocks", "pasta": "roblocks", "categorias": "all jogos" },
    { "nome": "Roblocks rosa", "pasta": "roblocksrosa", "categorias": "all jogos" },
    { "nome": "Safari", "pasta": "safari", "categorias": "all safari" },
    { "nome": "Safari Menina", "pasta": "safarimenina", "categorias": "all safari" },
    { "nome": "Sao Paulo", "pasta": "saopaulo", "categorias": "all times futebol" },
    { "nome": "Sereia Splash", "pasta": "sereiasplash", "categorias": "all filme menina" },
    { "nome": "Sky e Everest", "pasta": "skyeeverest", "categorias": "all animais desenhos" },
    { "nome": "Sonic", "pasta": "sonic", "categorias": "all jogos desenhos filme" },
    { "nome": "Sonic e Knuckles", "pasta": "soniceknuckles", "categorias": "all jogos desenhos filme" },
    { "nome": "Sonic e Shadow", "pasta": "soniceshadow", "categorias": "all jogos desenhos filme" },
    { "nome": "Stitch arco iris", "pasta": "stitcharcoiris", "categorias": "all desenhos filme stitch" },
    { "nome": "Stitch bolha chiclete", "pasta": "stitchbolhachiclete", "categorias": "all desenhos filme stitch" },
    { "nome": "Stitch e Angel", "pasta": "stitcheangel", "categorias": "all desenhos filme stitch" },
    { "nome": "Stitch e Angel fundo coracao", "pasta": "stitcheangelfundocoracao", "categorias": "all desenhos filme stitch" },
    { "nome": "Stitch flor", "pasta": "stitchflor", "categorias": "all desenhos filme stitch" },
    { "nome": "Stitch Milk Shake", "pasta": "stitchmilkshake", "categorias": "all desenhos filme stitch" },
    { "nome": "Stitch", "pasta": "stitch", "categorias": "all desenhos filme stitch" },
    { "nome": "Stray Kids", "pasta": "straykids", "categorias": "all k-pop musica" },
    { "nome": "Tardezinha", "pasta": "tardezinha", "categorias": "all diversos" },
    { "nome": "The Chosen", "pasta": "thechosen", "categorias": "all religiosos series" },
    { "nome": "Tres palavrinhas Menino", "pasta": "trespalavrinhasmenino", "categorias": "all religiosos meninos" },
    { "nome": "Tres palavrinhas Menina", "pasta": "trespalavrinhasmenina", "categorias": "all religiosos meninas" },
    { "nome": "Trolls", "pasta": "trolls", "categorias": "all desenhos filme" },
    { "nome": "Turma Tube", "pasta": "turmatube", "categorias": "all desenhos youtube" },
    { "nome": "Turma da Monica", "pasta": "turmadamonica", "categorias": "all desenhos" },
    { "nome": "Ursinho Pooh", "pasta": "ursinhopooh", "categorias": "all desenhos filme" },
    { "nome": "Ursinho Marron", "pasta": "ursinhomarron", "categorias": "all ursinho infantil" },
    { "nome": "Ursinhos carinhosos", "pasta": "ursinhoscarinhosos", "categorias": "all desenhos" },
    { "nome": "Valente", "pasta": "valente", "categorias": "all princesas filme disney" },
    { "nome": "Vera Arco-Iris", "pasta": "veraarcoiris", "categorias": "all desenhos" },
    { "nome": "Wandinha", "pasta": "wandinha", "categorias": "all filme" },
    { "nome": "Os Rosa", "pasta": "osrosa", "categorias": "all youtuber" },
    { "nome": "Baby Shark rosa", "pasta": "babysharkrosa", "categorias": "all fundodomar desenhos musica" },
    { "nome": "desenhos Boiadeirinha", "pasta": "desenhosboiadeirinha", "categorias": "all desenhos boiadeira" },
    { "nome": "Power Rangers", "pasta": "powerrangers", "categorias": "all desenhos filme" },
    { "nome": "Angel", "pasta": "angel", "categorias": "all desenhos filme stitch angel" },
    { "nome": "Urso Marrom", "pasta": "ursomarrom", "categorias": "all desenhos urso" },
    { "nome": "Romano Pirulito Liso", "pasta": "romanopirulitoliso", "categorias": "all romano pirulito liso" },
    { "nome": "Romano Retangular Liso", "pasta": "romanoretangularliso", "categorias": "all romano pirulito liso" },
    { "nome": "Romano Branco", "pasta": "romanobranco", "categorias": "all romano pirulito liso" },
    { "nome": "Romano Rose", "pasta": "romanorose", "categorias": "all romano pirulito liso" },
    { "nome": "Romano Marrom", "pasta": "romanomarrom", "categorias": "all romano pirulito liso" },
    { "nome": "Romano Azul bebe", "pasta": "romanoazulbebe", "categorias": "all romano pirulito liso" },
    { "nome": "Carnaval", "pasta": "carnaval", "categorias": "all datacomemorativa carnaval" },
    { "nome": "Homem de ferro", "pasta": "homemdeferro", "categorias": "all herois meninos" },
    { "nome": "Romano Liso", "pasta": "romanoliso", "categorias": "all romano pirulito liso" },
    { "nome": "Real Madri", "pasta": "realmadri", "categorias": "all time futebol" },
    { "nome": "Happy Birthday Azul e Dourado", "pasta": "happybirthdayazuledourado", "categorias": "all happybirthday" },
    { "nome": "Nossa Senhora", "pasta": "nossasenhora", "categorias": "all religioso" },
    { "nome": "Bento e Toto", "pasta": "bentoetoto", "categorias": "all desenhos meninos" }
]

def verificar_e_criar_pastas(caminho_imagens):
    print("=" * 60)
    print(" PROCESSANDO E CRIANDO PASTAS EM FALTA NO SEU SITE")
    print("=" * 60)
    
    try:
        pastas_reais = os.listdir(caminho_imagens)
    except FileNotFoundError:
        print("Erro: O caminho especificado não foi encontrado!")
        return

    pastas_reais_minusculo = {p.lower(): p for p in pastas_reais}
    pastas_criadas = 0
    erros_letra = 0

    for tema in bancoDadosTemas:
        pasta_codigo = tema["pasta"]
        nome_tema = tema["nome"]
        
        caminho_esperado = os.path.join(caminho_imagens, pasta_codigo)
        
        # Se a pasta não existe no local
        if not os.path.exists(caminho_esperado):
            
            # Caso ela já exista mas com letras maiúsculas/minúsculas trocadas
            if pasta_codigo.lower() in pastas_reais_minusculo:
                erros_letra += 1
                nome_real = pastas_reais_minusculo[pasta_codigo.lower()]
                print(f"⚠️ AVISO DE CAIXA: O tema '{nome_tema}' existe no computador como '{nome_real}'")
                print(f"   mas o código procura por '{pasta_codigo}'. (O Windows ignora isto, mas pode dar erro em servidores Linux).\n")
            
            # Se a pasta realmente não existir de forma alguma
            else:
                print(f"📁 A criar pasta para o tema: '{nome_tema}'")
                try:
                    os.makedirs(caminho_esperado)
                    print(f"   --> ✨ Pasta '{pasta_codigo}' criada com sucesso!")
                    pastas_criadas += 1
                except Exception as e:
                    print(f"   --> ❌ Falha ao tentar criar a pasta: {e}")

    print("=" * 60)
    print(f"🎉 Processo concluído!")
    print(f"   --> Novas pastas criadas: {pastas_criadas}")
    print(f"   --> Avisos de letras (Maiúsculas/Minúsculas): {erros_letra}")
    print("=" * 60)

if __name__ == "__main__":
    caminho = input("Digite o caminho completo da pasta 'Imagem' do seu projeto: ").strip()
    verificar_e_criar_pastas(caminho)