import os

# Lista com a sintaxe do Python para todas as chaves e valores
bancoDadosTemas = [
    { "nome": "1ª Volta ao Sol", "pasta": "1voltaaosol", "categorias": "all animais desenhos" },
    { "nome": "101 Dálmatas", "pasta": "101dalmatas", "categorias": "all animais desenhos" },
    { "nome": "15 anos", "pasta": "15anos", "categorias": "all diversos" },
    { "nome": "1ª Eucaristia", "pasta": "1eucaristia", "categorias": "all religioso" },
    { "nome": "3 Palavrinhas Menina", "pasta": "3palavrinhasmenina", "categorias": "all religiosos" },
    { "nome": "3 Palavrinhas Menino", "pasta": "3palavrinhasmenino", "categorias": "all religiosos" },
    { "nome": "Abelhinha", "pasta": "abelhinha", "categorias": "all animais desenhos" },
    { "nome": "Alice no pais das maravilhas cute", "pasta": "alicenopaisdasmaravilhascute", "categorias": "all princesas contodefadas filme disney" },
    { "nome": "Amo Meu Tete Menino", "pasta": "amomeutetemenino", "categorias": "all baby cute" },
    { "nome": "Ana Castela", "pasta": "anacastela", "categorias": "all boiadeira musica" },
    { "nome": "Angel", "pasta": "angel", "categorias": "all desenhos filme stitch angel" },
    { "nome": "Animatronics", "pasta": "animatronics", "categorias": "all jogos" },
    { "nome": "Ano novo", "pasta": "anonovo", "categorias": "all anonovo fimdeano datacomemorativa" },
    { "nome": "Arco Vazado Desconstruído", "pasta": "arcovazado_desconstruido", "categorias": "all arcovazado" },
    { "nome": "Arco Vazado Simples", "pasta": "arcovazado_simples", "categorias": "all arcovazado" },
    { "nome": "Ariel", "pasta": "ariel", "categorias": "all princesas disney" },
    { "nome": "Ariel 2", "pasta": "ariel2", "categorias": "all princesas disney" },
    { "nome": "Arraia marron", "pasta": "arraiamarrom", "categorias": "all arraia datacomemorativa" },
    { "nome": "Arraia rosa", "pasta": "arraiarosa", "categorias": "all arraia datacomemorativa" },
    { "nome": "Asa neon", "pasta": "asaneon", "categorias": "all diversos" },
    { "nome": "Astronauta", "pasta": "astronauta", "categorias": "all espaco desenhos" },
    { "nome": "BTS", "pasta": "bts", "categorias": "all k-pop musica" },
    { "nome": "Baby Shark Azul", "pasta": "babysharkazul", "categorias": "all fundodomar desenhos musica" },
    { "nome": "Baby Shark Rosa", "pasta": "babysharkrosa", "categorias": "all fundodomar desenhos musica" },
    { "nome": "Bailarina", "pasta": "bailarina", "categorias": "all meninas bale" },
    { "nome": "Barbie", "pasta": "barbie", "categorias": "all meninos desenhos filme boneca" },
    { "nome": "Batizado Anjinho", "pasta": "batizadoanjinho", "categorias": "all religiosos batizado" },
    { "nome": "Batizado Beje", "pasta": "batizadobeje", "categorias": "all religiosos batizado" },
    { "nome": "Batizado Divino Espirito Santo Arabesco", "pasta": "batizadodivinoespiritosantoarabesco", "categorias": "all religiosos batizado" },
    { "nome": "Batizado Divino Espirito Santo", "pasta": "batizadodivinoespiritosanto", "categorias": "all religiosos batizado" },
    { "nome": "Batizado Lilas", "pasta": "batizadolilas", "categorias": "all religiosos batizado" },
    { "nome": "Batizado Rosa", "pasta": "batizadorosa", "categorias": "all religiosos batizado" },
    { "nome": "Batizado Verde", "pasta": "batizadoverde", "categorias": "all religiosos batizado" },
    { "nome": "Batizado Azul", "pasta": "batizadoazul", "categorias": "all religiosos batizado" },
    { "nome": "Batizado", "pasta": "batizado", "categorias": "all religiosos batizado" },
    { "nome": "Batman", "pasta": "batman", "categorias": "all herois filme desenhos" },
    { "nome": "Bee movie", "pasta": "beemovie", "categorias": "all filme animais" },
    { "nome": "Bela adormecida", "pasta": "belaadormecida", "categorias": "all princesas contodefadas filme disney" },
    { "nome": "Bela e a Fera", "pasta": "belaeafera", "categorias": "all princesas contodefadas filme disney" },
    { "nome": "Bento e Totó", "pasta": "bentoetoto", "categorias": "all desenhos meninos" },
    { "nome": "BeyBlade", "pasta": "beyblade", "categorias": "all desenhos" },
    { "nome": "Blazze", "pasta": "blazze", "categorias": "all corrida desenhos" },
    { "nome": "Bluey e bingo aniversario", "pasta": "blueyebingoaniversario", "categorias": "all desenhos animais" },
    { "nome": "Bluey e bingo", "pasta": "blueyebingo", "categorias": "all desenhos animais" },
    { "nome": "Bob Esponja", "pasta": "bobesponja", "categorias": "all desenhos fundodomar" },
    { "nome": "Bobbie Goods", "pasta": "bobbiegoods", "categorias": "all diversos" },
    { "nome": "Boiadeira", "pasta": "boiadeira", "categorias": "all boiadeira" },
    { "nome": "Bolofofos", "pasta": "bolofofos", "categorias": "all desenhos musicas" },
    { "nome": "Bombeiro", "pasta": "bombeiro", "categorias": "all bombeiro" },
    { "nome": "Borboleta Roxa", "pasta": "borboletaroxa", "categorias": "all borboletas animais" },
    { "nome": "Borboleta e Flor Lilas", "pasta": "borboletaeflorlilas", "categorias": "all borboletas animais" },
    { "nome": "Borboletas Azuis", "pasta": "borboletasazuis", "categorias": "all borboletas animais" },
    { "nome": "Bosque Encantado", "pasta": "bosqueencantado", "categorias": "all diversos cute animais" },
    { "nome": "Boteco cerveja", "pasta": "botecocerveja", "categorias": "all boteco diversos" },
    { "nome": "Boteco", "pasta": "boteco", "categorias": "all boteco diversos" },
    { "nome": "Branca de neve cute", "pasta": "brancadenevecute", "categorias": "all princesas contodefadas filme disney cute" },
    { "nome": "Branca de Neve", "pasta": "brancadeneve", "categorias": "all princesas contodefadas filme disney cute" },
    { "nome": "CR7", "pasta": "cr7", "categorias": "all futebol jogador" },
    { "nome": "Caminhao Azul e Laranja", "pasta": "caminhao", "categorias": "all diversos desenhos veiculos" },
    { "nome": "Capitao America", "pasta": "capitaoamerica", "categorias": "all herois filme desenhos" },
    { "nome": "Capivara", "pasta": "capivara", "categorias": "all animais diversos" },
    { "nome": "Capivara Arco-Iris", "pasta": "capivaraarcoiris", "categorias": "all animais diversos" },
    { "nome": "Carmed", "pasta": "carmed", "categorias": "all doce labial" },
    { "nome": "Carnaval", "pasta": "carnaval", "categorias": "all datacomemorativa carnaval" },
    { "nome": "Casa magica da gabby", "pasta": "casamagicadagabby", "categorias": "all desenhos magia" },
    { "nome": "Castelo Ra-tim-bum", "pasta": "casteloratimbum", "categorias": "all desenhos diversos" },
    { "nome": "Cavalo", "pasta": "cavalo", "categorias": "all animais" },
    { "nome": "Cerejinha", "pasta": "cerejinha", "categorias": "all frutas" },
    { "nome": "Chá Revelacao Menino Menina", "pasta": "charevelacaomeninomenina", "categorias": "all charevelacao" },
    { "nome": "Chá Revelacao Urso Azul e Rosa", "pasta": "charevelacaoursoazulerosa", "categorias": "all charevelacao" },
    { "nome": "Chá Revelacao Urso Roxo e Verde", "pasta": "charevelacaoursoroxoeverde", "categorias": "all charevelacao" },
    { "nome": "Chá Revelacao", "pasta": "charevelacao", "categorias": "all charevelacao" },
    { "nome": "Chá de Casa Nova", "pasta": "chadecasanova", "categorias": "all chadecasanova" },
    { "nome": "Chá de Lingerie", "pasta": "chadelingerie", "categorias": "all chalingerie" },
    { "nome": "Chá de Panela", "pasta": "chadepanela", "categorias": "all chapanela" },
    { "nome": "Chá de Bebe Arraia Rosa", "pasta": "chadebebearraiarosa", "categorias": "all chadebebe personalizada" },
    { "nome": "Chá de Bebe Azul", "pasta": "chadebebeazul", "categorias": "all chadebebe" },
    { "nome": "Chá de Bebe Lilas", "pasta": "chadebebelilas", "categorias": "all chadebebe" },
    { "nome": "Chá de Bebe Rosa", "pasta": "chadebeberosa", "categorias": "all chadebebe" },
    { "nome": "Chá de Bebe Verde", "pasta": "chadebebeverde", "categorias": "all chadebebe" },
    { "nome": "Chaves Baby", "pasta": "chavesbaby", "categorias": "all desenhos" },
    { "nome": "Churrasco", "pasta": "churrasco", "categorias": "all churrasco" },
    { "nome": "Cinderela", "pasta": "cinderela", "categorias": "all princesas filme contodefadas disney" },
    { "nome": "Circo Rosa", "pasta": "circorosa", "categorias": "all circo" },
    { "nome": "Corinthians", "pasta": "corinthians", "categorias": "all times futebol" },
    { "nome": "Corinthians Laranja", "pasta": "corinthianslaranja", "categorias": "all times futebol" },
    { "nome": "De repente 30", "pasta": "derepente30", "categorias": "all diversos" },
    { "nome": "Demon Slayer", "pasta": "demonslayer", "categorias": "all anime" },
    { "nome": "Desenho Boiadeirinha", "pasta": "desenhoboiadeirinha", "categorias": "all desenhos boiadeira" },
    { "nome": "Dia das Maes", "pasta": "diadasmaes", "categorias": "all datacomemorativa" },
    { "nome": "Dia das Mães Rosas Vermelhas", "pasta": "diadasmaesrosasvermelhas", "categorias": "all datacomemorativa" },
    { "nome": "Dia das Mães Bebe menino no colo", "pasta": "diadasmaesbebemeninocolo", "categorias": "all datacomemorativa" },
    { "nome": "Dia dos Pais", "pasta": "diadospais", "categorias": "all datacomemorativa" },
    { "nome": "Dinossauro", "pasta": "dinossauro", "categorias": "all dinossauro animais" },
    { "nome": "Dinossauro Jurassic Park", "pasta": "dinossaurojurassicpark", "categorias": "all dinossauro animais" },
    { "nome": "Dinossauros Baby Rosa", "pasta": "dinossaurobabyrosa", "categorias": "all dinossauro animais meninas" },
    { "nome": "Dinossauros Baby", "pasta": "dinossaurosbaby", "categorias": "all dinossauro animais" },
    { "nome": "Divertidamente", "pasta": "divertidamente", "categorias": "all filme contodefadas" },
    { "nome": "Doceria", "pasta": "doceria", "categorias": "all doces diversos" },
    { "nome": "Dragon Ball", "pasta": "dragonball", "categorias": "all desenhos" },
    { "nome": "Dragão Medieval", "pasta": "dragaomedieval", "categorias": "all desenhos" },
    { "nome": "Empresarial", "pasta": "empresarial", "categorias": "all empresas" },
    { "nome": "Enaldinho", "pasta": "enaldinho", "categorias": "all youtuber" },
    { "nome": "Enrolados", "pasta": "enrolados", "categorias": "all princesas contodefadas filme" },
    { "nome": "Encanto", "pasta": "encanto", "categorias": "all princesas contodefadas filme" },
    { "nome": "Eu amo tete menina", "pasta": "euamotetemenina", "categorias": "all cute diversos" },
    { "nome": "Eu amo tete menino", "pasta": "euamotetemenino", "categorias": "all cute diversos" },
    { "nome": "Fazendinha Azul", "pasta": "fazendinhaazul", "categorias": "all fazendinha" },
    { "nome": "Fazendinha Rosa", "pasta": "fazendinharosa", "categorias": "all fazendinha" },
    { "nome": "Fazendinha Vermelha", "pasta": "fazendinhavermelha", "categorias": "all fazendinha" },
    { "nome": "Festa Junina", "pasta": "festajunina", "categorias": "all arraia" },
    { "nome": "Fini fundo branco", "pasta": "finifundobranco", "categorias": "all doces diversos" },
    { "nome": "Fini fundo vermelho", "pasta": "finifundovermelho", "categorias": "all doces diversos" },
    { "nome": "Flamengo", "pasta": "flamengo", "categorias": "all times futebol" },
    { "nome": "Flamingo", "pasta": "flamingo", "categorias": "all animais" },
    { "nome": "Flor Lilas e borboleta", "pasta": "florlilaseborboleta", "categorias": "all flores borboletas" },
    { "nome": "Flork eu te amo", "pasta": "florkeuteamo", "categorias": "all diversos" },
    { "nome": "Free Fire", "pasta": "freefire", "categorias": "all jogos" },
    { "nome": "Frozen", "pasta": "frozen", "categorias": "all princesas filme contodefadas disney" },
    { "nome": "Frutas", "pasta": "frutas", "categorias": "all frutas" },
    { "nome": "Fundo do mar", "pasta": "fundodomar", "categorias": "all fundodomar" },
    { "nome": "Futebol menina", "pasta": "futebolmenina", "categorias": "all times futebol feminino" },
    { "nome": "Futebol", "pasta": "futebol", "categorias": "all times futebol" },
    { "nome": "Galinha Pintadinha", "pasta": "galinhapintadinha", "categorias": "all desenhos musica" },
    { "nome": "Galinha Pintadinha Cute", "pasta": "galinhapintadinhacute", "categorias": "all desenhos musica cute" },
    { "nome": "Gamer", "pasta": "gamer", "categorias": "all game diversos" },
    { "nome": "Gi Turma Luccas Neto", "pasta": "giturmaluccasneto", "categorias": "all youtuber desenhos" },
    { "nome": "Godzilla vs King Kong", "pasta": "godzillavskingkong", "categorias": "all filme contodefadas" },
    { "nome": "Goku SSJ3", "pasta": "gokussj3", "categorias": "all diversos" },
    { "nome": "Gratidao", "pasta": "gratidao", "categorias": "all diversos" },
    { "nome": "Grinch", "pasta": "grinch", "categorias": "all filme desenho menino" },
    { "nome": "Groot", "pasta": "groot", "categorias": "all filme cute" },
    { "nome": "Guerreiras do K-pop", "pasta": "guerreirasdokpop", "categorias": "all k-pop musica filme" },
    { "nome": "Halloween Abobora", "pasta": "halloweenabobora", "categorias": "all datacomemorativa halloween" },
    { "nome": "Halloween Castelo Laranja", "pasta": "halloweencastelolaranja", "categorias": "all datacomemorativa halloween" },
    { "nome": "Halloween Castelo Roxo", "pasta": "halloweencasteloroxo", "categorias": "all datacomemorativa halloween" },
    { "nome": "Happy Birthday Azul e Dourado", "pasta": "happybirthdayazuledourado", "categorias": "all happybirthday" },
    { "nome": "Happy Birthday Glitter Pink", "pasta": "happybirthdayglitterpink", "categorias": "all happybirthday glitter" },
    { "nome": "Happy Birthday Laranja e pink", "pasta": "happybirthdaylaranjaepink", "categorias": "all happybirthday" },
    { "nome": "Happy Birthday Marssala", "pasta": "happybirthdaymarssala", "categorias": "all happybirthday" },
    { "nome": "Happy Birthday Azul Arabesco Dourado", "pasta": "happybirthdayazularabescodourado", "categorias": "all happybirthday glitter" },
    { "nome": "Happy Birthday Preto Rose Glitter", "pasta": "happybirthdayroseglitter", "categorias": "all happybirthday glitter" },
    { "nome": "Happy Birthday Azul e Arata", "pasta": "happybirthdayazuleprata", "categorias": "all happybirthday" },
    { "nome": "Happy Birthday Glitter Rose", "pasta": "happybirthdayglitterrose", "categorias": "all happybirthday glitter" },
    { "nome": "Happy Birthday Lantejoula Lilas", "pasta": "happybirthdaylantejoulalilas", "categorias": "all happybirthday" },
    { "nome": "Happy Birthday Lantejoula Rosa", "pasta": "happybirthdaylantejoularosa", "categorias": "all happybirthday" },
    { "nome": "Happy Birthday Preto e Dourado", "pasta": "happybirthdaypretoedourado", "categorias": "all happybirthday" },
    { "nome": "Happy Birthday Vermelho e Dourado", "pasta": "happybirthdayvermelhoedourado", "categorias": "all happybirthday" },
    { "nome": "Harry Potter", "pasta": "harrypotter", "categorias": "all filme contodefadas magia" },
    { "nome": "Hello Kitty", "pasta": "hellokitty", "categorias": "all desenhos" },
    { "nome": "Heróis", "pasta": "herois", "categorias": "all herois filme cute" },
    { "nome": "Homem Aranha Cute", "pasta": "homemaranhacute", "categorias": "all herois filme cute" },
    { "nome": "Homem Aranha", "pasta": "homemaranha", "categorias": "all herois filme" },
    { "nome": "Homem de Ferro", "pasta": "homemdeferro", "categorias": "all herois filme" },
    { "nome": "HotWheels", "pasta": "hotwheels", "categorias": "all corrida desenhos veiculos" },
    { "nome": "Hulk", "pasta": "hulk", "categorias": "all herois meninos" },
    { "nome": "Ilhama", "pasta": "ilhama", "categorias": "all animais" },
    { "nome": "Illit K-POP", "pasta": "illit", "categorias": "all k-pop musica" },
    { "nome": "Jardim de Borboletas", "pasta": "jardimdeborboletas", "categorias": "all jardim borboletas" },
    { "nome": "Jujutsi Kaisen", "pasta": "jujutsokaisen", "categorias": "all anime" },
    { "nome": "Kuromi e Melody", "pasta": "kuromiemelody", "categorias": "all desenhos" },
    { "nome": "Labubu menina", "pasta": "labubumenina", "categorias": "all desenhos" },
    { "nome": "Labubu menino", "pasta": "labubumenino", "categorias": "all desenhos" },
    { "nome": "Lady Budy", "pasta": "ladybudy", "categorias": "all desenhos filme" },
    { "nome": "Lantejoula Dourado", "pasta": "lantejouladourado", "categorias": "all lantejoula natal" },
    { "nome": "Lantejoula Prata", "pasta": "lantejoulaprata", "categorias": "all lantejoula natal" },
    { "nome": "Lantejoula Vermelha", "pasta": "lantejoulavermelha", "categorias": "all lantejoula natal" },
    { "nome": "Lanterna Verde", "pasta": "lanternaverde", "categorias": "all herois filme" },
    { "nome": "Lavanda", "pasta": "lavanda", "categorias": "all flores" },
    { "nome": "Laço Preto Fundo Branco", "pasta": "lacopretofundobranco", "categorias": "all lacos" },
    { "nome": "Laço rosa Fundo Branco", "pasta": "lacorosafundobranco", "categorias": "all lacos" },
    { "nome": "Liga da Justica baby", "pasta": "ligadajusticababy", "categorias": "all herois cute" },
    { "nome": "Liso Azul Royal", "pasta": "lisoazulroyal", "categorias": "all cores" },
    { "nome": "Liso Branco", "pasta": "lisobranco", "categorias": "all liso cores" },
    { "nome": "Liso Pirulito Azul Bebe", "pasta": "lisopirulitoazulbebe", "categorias": "all cores" },
    { "nome": "Liso Rosa", "pasta": "lisorosa", "categorias": "all cores" },
    { "nome": "Magali", "pasta": "magali", "categorias": "all desenhos" },
    { "nome": "MagaliFundo Amarelo", "pasta": "magalifundoamarelo", "categorias": "all desenhos" },
    { "nome": "Magali Rosa", "pasta": "magalirosa", "categorias": "all desenhos" },
    { "nome": "Margarida", "pasta": "margarida", "categorias": "all flores" },
    { "nome": "Maria Clara e JP", "pasta": "mariaclaraejp", "categorias": "all youtuber desenhos" },
    { "nome": "Masha e o Urso", "pasta": "mashaeourso", "categorias": "all desenhos" },
    { "nome": "Meu mundo doce com Jesus", "pasta": "meumundodocecomjesus", "categorias": "all religiosos" },
    { "nome": "Mickey", "pasta": "mickey", "categorias": "all desenhos disney" },
    { "nome": "MineCraft", "pasta": "minecraft", "categorias": "all jogos" },
    { "nome": "Minions 2", "pasta": "minions2", "categorias": "all filme desenhos" },
    { "nome": "Minions", "pasta": "minions", "categorias": "all filme desenhos" },
    { "nome": "Minnie rosa", "pasta": "minnierosa", "categorias": "all desenhos disney" },
    { "nome": "Minnie vermelha", "pasta": "minnievermelha", "categorias": "all desenhos disney" },
    { "nome": "Moana 2", "pasta": "moana2", "categorias": "all princesas filme contodefadas disney" },
    { "nome": "Moana baby", "pasta": "moanababy", "categorias": "all princesas filme contodefadas cute disney" },
    { "nome": "Moana", "pasta": "moana", "categorias": "all princesas filme contodefadas disney" },
    { "nome": "Monstros SA", "pasta": "monstrossa", "categorias": "all desenhos filme disney" },
    { "nome": "Mulher Maravilha Cute", "pasta": "mulhermaravilhacute", "categorias": "all herois filme cute" },
    { "nome": "Mundo Bita", "pasta": "mundobita", "categorias": "all desenhos musica" },
    { "nome": "Naruto", "pasta": "naruto", "categorias": "all anime" },
    { "nome": "Natal", "pasta": "natal", "categorias": "all natal datacomemorativa" },
    { "nome": "Natal Papai e Mamãe Noel", "pasta": "natalpapaiemamaenoel", "categorias": "all natal datacomemorativa" },
    { "nome": "Noivado", "pasta": "noivado", "categorias": "all noivado" },
    { "nome": "Nossa Senhora Aparecida", "pasta": "nossasenhoraaparecida", "categorias": "all religioso" },
    { "nome": "NumberBlocks", "pasta": "numberblocks", "categorias": "all desenhos" },
    { "nome": "One Piece", "pasta": "onepiece", "categorias": "all anime desenho" },
    { "nome": "Os Rosas", "pasta": "osrosas", "categorias": "all youtuber" },
    { "nome": "Os Rosas Desenho", "pasta": "osrosadesenho", "categorias": "all youtuber" },
    { "nome": "Palmeiras", "pasta": "palmeiras", "categorias": "all times futebol" },
    { "nome": "Pantera Negra", "pasta": "panteranegra", "categorias": "all herois filme" },
    { "nome": "Pascoa Amarelo com ovos rosa e azul", "pasta": "pascoaamarelocomovosrosaeazul", "categorias": "all pascoa" },
    { "nome": "Patati e Patata", "pasta": "patatiepatata", "categorias": "all desenhos musicas" },
    { "nome": "Patinho Colorido", "pasta": "patinhocolorido", "categorias": "all desenhos musica" },
    { "nome": "Patrulha Canina", "pasta": "patrulhacanina", "categorias": "all animais desenhos" },
    { "nome": "Pepa pig", "pasta": "pepapig", "categorias": "all desenhos animais" },
    { "nome": "Pequeno Principe", "pasta": "pequenoprincipe", "categorias": "all desenhos" },
    { "nome": "Personalizado", "pasta": "personalizado", "categorias": "all personalizados" },
    { "nome": "PjMask", "pasta": "pjmask", "categorias": "all desenhos" },
    { "nome": "Pocoyo", "pasta": "pocoyo", "categorias": "all desenhos" },
    { "nome": "Poderosa Chefinha", "pasta": "poderosachefinha", "categorias": "all filme desenhos" },
    { "nome": "Poderoso Chefinho", "pasta": "poderosochefinho", "categorias": "all filme desenhos" },
    { "nome": "Pokemon", "pasta": "pokemon", "categorias": "all desenhos animais" },
    { "nome": "Pool Party Azul", "pasta": "poolpartyazul", "categorias": "all piscina" },
    { "nome": "Pool Party Rosa", "pasta": "poolpartyrosa", "categorias": "all piscina" },
    { "nome": "Power Rangers", "pasta": "powerrangers", "categorias": "all desenhos filme" },
    { "nome": "Princesa Sofia", "pasta": "princesasofia", "categorias": "all disney filme desenhos" },
    { "nome": "Princesa Tiana", "pasta": "princesatiana", "categorias": "all princesas filme desenhos disney" },
    { "nome": "Princesas Disney", "pasta": "princesasdisney", "categorias": "all disney filme desenhos" },
    { "nome": "Real Madri", "pasta": "realmadri", "categorias": "all time futebol" },
    { "nome": "Rei Leao", "pasta": "reileao", "categorias": "all animais desenhos filme" },
    { "nome": "Relampago Mcqueen", "pasta": "relampagomcqueen", "categorias": "all filme corrida veiculos" },
    { "nome": "Roblox Menina", "pasta": "robloxmenina", "categorias": "all jogos" },
    { "nome": "Roblox Minino", "pasta": "robloxmenino", "categorias": "all jogos" },
    { "nome": "Romano Liso", "pasta": "romanoliso", "categorias": "all romano pirulito liso" },
    { "nome": "Romano Meia Lua", "pasta": "romanomeialua", "categorias": "all romano pirulito liso" },
    { "nome": "Romano Pirulito Laranja", "pasta": "romanopirulitolaranja", "categorias": "all romano pirulito liso" },
    { "nome": "Romano Pirulito Pink", "pasta": "romanopirulitopink", "categorias": "all romano pirulito liso" },
    { "nome": "Romano Retangular", "pasta": "romanoretangular", "categorias": "all romano pirulito liso" },
    { "nome": "Safari Menina", "pasta": "safarimenina", "categorias": "all safari" },
    { "nome": "Safari Menino", "pasta": "safarimenino", "categorias": "all safari" },
    { "nome": "Sao Paulo", "pasta": "saopaulo", "categorias": "all times futebol" },
    { "nome": "Sereia Splash", "pasta": "sereiasplash", "categorias": "all filme menina" },
    { "nome": "Sky e Everest", "pasta": "skyeeverest", "categorias": "all animais desenhos" },
    { "nome": "Sonic e Knuckles", "pasta": "soniceknuckles", "categorias": "all jogos desenhos filme" },
    { "nome": "Sonic e Shadow", "pasta": "soniceshadow", "categorias": "all jogos desenhos filme" },
    { "nome": "Sonic", "pasta": "sonic", "categorias": "all jogos desenhos filme" },
    { "nome": "Stitch Milk Shake", "pasta": "stitchmilkshake", "categorias": "all desenhos filme stitch" },
    { "nome": "Stitch Arco Iris", "pasta": "stitcharcoiris", "categorias": "all desenhos filme stitch" },
    { "nome": "Stitch Chiclete", "pasta": "stitchchiclete", "categorias": "all desenhos filme stitch" },
    { "nome": "Stitch e Angel coracao", "pasta": "stitcheangelcoracao", "categorias": "all desenhos filme stitch" },
    { "nome": "Stitch e Angel", "pasta": "stitcheangel", "categorias": "all desenhos filme stitch" },
    { "nome": "Stitch flor", "pasta": "stitchflor", "categorias": "all desenhos filme stitch" },
    { "nome": "Stitch", "pasta": "stitch", "categorias": "all desenhos filme stitch" },
    { "nome": "Stray Kids", "pasta": "straykids", "categorias": "all k-pop musica" },
    { "nome": "Tardezinha", "pasta": "tardezinha", "categorias": "all diversos" },
    { "nome": "The Chosen", "pasta": "thechosen", "categorias": "all religiosos series" },
    { "nome": "Trolls", "pasta": "trolls", "categorias": "all desenhos filme" },
    { "nome": "Turma Tube", "pasta": "turmatube", "categorias": "all desenhos youtube" },
    { "nome": "Turma da Monica", "pasta": "turmadamonica", "categorias": "all desenhos" },
    { "nome": "Ursinho Marron", "pasta": "ursinhomarron", "categorias": "all ursinho infantil" },
    { "nome": "Ursinho Pooh Baby", "pasta": "ursinhopoohbaby", "categorias": "all desenhos filme cute" },
    { "nome": "Ursinho Pooh", "pasta": "ursinhopooh", "categorias": "all desenhos filme" },
    { "nome": "Ursinhos Carinhosos", "pasta": "ursinhoscarinhosos", "categorias": "all desenhos" },
    { "nome": "Valente", "pasta": "valente", "categorias": "all princesas filme disney" },
    { "nome": "Vera Arco-Iris", "pasta": "veraarcoiris", "categorias": "all desenhos" },
    { "nome": "Wandinha", "pasta": "wandinha", "categorias": "all filme" },
    { "nome": "lilas Glitter", "pasta": "lilasglitter", "categorias": "all glitter" },
    { "nome": "Raposinha", "pasta": "raposinha", "categorias": "all animais" },
    { "nome": "Yoshi", "pasta": "yoshi", "categorias": "all desenho jogo" }
]

def verificar_e_criar_pastas(caminho_imagens):
    print("=" * 60)
    print(" PROCESSANDO E CRIANDO PASTAS EM FALTA NO SEU SITE")
    print("=" * 60)
    
    try:
        pastas_reais = os.listdir(caminho_imagens)
    except FileNotFoundError:
        print("Erro: O caminho especificado não foi encontrado!")
        return

    pastas_reais_minusculo = {p.lower(): p for p in pastas_reais}
    pastas_criadas = 0
    erros_letra = 0

    for tema in bancoDadosTemas:
        pasta_codigo = tema["pasta"]
        nome_tema = tema["nome"]
        
        caminho_esperado = os.path.join(caminho_imagens, pasta_codigo)
        
        # Se a pasta não existe no local
        if not os.path.exists(caminho_esperado):
            
            # Caso ela já exista mas com letras maiúsculas/minúsculas trocadas
            if pasta_codigo.lower() in pastas_reais_minusculo:
                erros_letra += 1
                nome_real = pastas_reais_minusculo[pasta_codigo.lower()]
                print(f"⚠️ AVISO DE CAIXA: O tema '{nome_tema}' existe no computador como '{nome_real}'")
                print(f"   mas o código procura por '{pasta_codigo}'. (O Windows ignora isto, mas pode dar erro em servidores Linux).\n")
            
            # Se a pasta realmente não existir de forma alguma
            else:
                print(f"📁 A criar pasta para o tema: '{nome_tema}'")
                try:
                    os.makedirs(caminho_esperado)
                    print(f"   --> ✨ Pasta '{pasta_codigo}' criada com sucesso!")
                    pastas_criadas += 1
                except Exception as e:
                    print(f"   --> ❌ Falha ao tentar criar a pasta: {e}")

    print("=" * 60)
    print(f"🎉 Processo concluído!")
    print(f"   --> Novas pastas criadas: {pastas_criadas}")
    print(f"   --> Avisos de letras (Maiúsculas/Minúsculas): {erros_letra}")
    print("=" * 60)

if __name__ == "__main__":
    caminho = input("Digite o caminho completo da pasta 'Imagem' do seu projeto: ").strip()
    verificar_e_criar_pastas(caminho)