name: Publicar site no HostGator

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Publicar no HostGator
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código do GitHub
        uses: actions/checkout@v6

      - name: Publicar via FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.4.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          port: 21
          server-dir: ./
          dangerous-clean-slate: false
          exclude: |
            **/.git*
            **/.git*/**
            **/.github/**
